import Head from 'next/head';
import axios from 'axios';
import ArticleList from '../components/ArticleList';
import styles from '../styles/Layout.module.css';

export default function Home({ articles }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>WebDev Newz</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='keywords' content='web development, programming' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<ArticleList articles={articles} />
		</div>
	);
}

export const getStaticProps = async () => {
	try {
		const response = await axios.get(
			'https://jsonplaceholder.typicode.com/posts?_limit=6'
		);
		if (response.status >= 400) throw new Error('api error');
		return {
			props: { articles: response.data },
		};
	} catch (err) {
		console.log('getStaticProps error ==>', err);
	}
};
